use std::io::Result;
use std::path::{Path, PathBuf};

fn main() -> Result<()> {
    println!("cargo:rerun-if-changed=proto");
    let proto_files = [
        "proto/decentraland/sdk/development/local_development.proto",
        "proto/decentraland/kernel/comms/rfc5/ws_comms.proto",
    ];
    let mut config = prost_build::Config::new();
    config.compile_protos(&proto_files, &["proto"])?;
    generate_component_schema()?;
    generate_abgen_embed()?;
    Ok(())
}

/// Compile the vendored @dcl/protocol component protos into a static schema
/// table (messages, enums, component ids) that src/crdt_gen.rs uses to
/// serialize composite JSON into main.crdt without node or @dcl/inspector.
fn generate_component_schema() -> Result<()> {
    use prost::Message;

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let comp_dir = Path::new("proto/decentraland/sdk/components");
    let mut protos: Vec<PathBuf> = std::fs::read_dir(comp_dir)?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("proto"))
        .collect();
    protos.sort();

    let descriptor_path = out_dir.join("components_descriptor.bin");
    let gen_dir = out_dir.join("components-prost-gen");
    std::fs::create_dir_all(&gen_dir)?;
    let mut config = prost_build::Config::new();
    config.file_descriptor_set_path(&descriptor_path);
    config.out_dir(&gen_dir); // generated Rust types are unused; only the descriptor set matters
    config.compile_protos(&protos, &[PathBuf::from("proto")])?;

    let fds = prost_types::FileDescriptorSet::decode(&std::fs::read(&descriptor_path)?[..])
        .expect("decoding the component FileDescriptorSet");

    // First pass: assign stable indexes to every message and enum (nested included).
    let mut msg_index: Vec<(String, prost_types::DescriptorProto)> = Vec::new();
    let mut enum_index: Vec<(String, prost_types::EnumDescriptorProto)> = Vec::new();
    for file in &fds.file {
        let pkg = file.package();
        for m in &file.message_type {
            collect_messages(pkg, m, &mut msg_index, &mut enum_index);
        }
        for e in &file.enum_type {
            enum_index.push((format!("{pkg}.{}", e.name()), e.clone()));
        }
    }
    let msg_pos = |full: &str| msg_index.iter().position(|(n, _)| n == full);
    let enum_pos = |full: &str| enum_index.iter().position(|(n, _)| n == full);

    // Second pass: emit the static tables.
    let mut src =
        String::from("// @generated by build.rs from proto/decentraland/sdk/components\n");
    src.push_str("pub(crate) static MESSAGES: &[MsgDef] = &[\n");
    for (full, m) in &msg_index {
        let map_entry = m.options.as_ref().is_some_and(|o| o.map_entry());
        let mut fields: Vec<&prost_types::FieldDescriptorProto> = m.field.iter().collect();
        fields.sort_by_key(|f| f.number());
        src.push_str(&format!(
            "    MsgDef {{ name: {full:?}, map_entry: {map_entry}, fields: &[\n"
        ));
        for f in fields {
            use prost_types::field_descriptor_proto::{Label, Type};
            let repeated = f.label() == Label::Repeated;
            let optional = f.proto3_optional();
            let strip = |s: &str| s.trim_start_matches('.').to_string();
            let kind = match f.r#type() {
                Type::Double => "FieldKind::Double".into(),
                Type::Float => "FieldKind::Float".into(),
                Type::Int32 => "FieldKind::Int32".into(),
                Type::Int64 => "FieldKind::Int64".into(),
                Type::Uint32 => "FieldKind::Uint32".into(),
                Type::Uint64 => "FieldKind::Uint64".into(),
                Type::Sint32 => "FieldKind::Sint32".into(),
                Type::Sint64 => "FieldKind::Sint64".into(),
                Type::Fixed32 => "FieldKind::Fixed32".into(),
                Type::Fixed64 => "FieldKind::Fixed64".into(),
                Type::Sfixed32 => "FieldKind::Sfixed32".into(),
                Type::Sfixed64 => "FieldKind::Sfixed64".into(),
                Type::Bool => "FieldKind::Bool".into(),
                Type::String => "FieldKind::Str".into(),
                Type::Bytes => "FieldKind::Bytes".into(),
                Type::Enum => {
                    let full = strip(f.type_name());
                    let idx = enum_pos(&full)
                        .unwrap_or_else(|| panic!("enum {full} not found in descriptor set"));
                    format!("FieldKind::Enum({idx})")
                }
                Type::Message | Type::Group => {
                    let full = strip(f.type_name());
                    let idx = msg_pos(&full)
                        .unwrap_or_else(|| panic!("message {full} not found in descriptor set"));
                    format!("FieldKind::Msg({idx})")
                }
            };
            // proto3 packs numeric repeated fields unless packed=false is explicit
            let packable = !matches!(
                f.r#type(),
                Type::String | Type::Bytes | Type::Message | Type::Group
            );
            let packed =
                repeated && packable && f.options.as_ref().and_then(|o| o.packed) != Some(false);
            // proto3 optional is implemented as a synthetic oneof; only real
            // oneofs get the ts-proto {$case} JSON shape
            let oneof = match f.oneof_index {
                Some(i) if !optional => {
                    let name = m.oneof_decl[i as usize].name();
                    format!("Some({:?})", camel_case(name))
                }
                _ => "None".to_string(),
            };
            src.push_str(&format!(
                "        FieldDef {{ number: {}, json_name: {:?}, kind: {kind}, repeated: {repeated}, packed: {packed}, optional: {optional}, oneof: {oneof} }},\n",
                f.number(),
                f.json_name(),
            ));
        }
        src.push_str("    ] },\n");
    }
    src.push_str("];\n");

    src.push_str("pub(crate) static ENUMS: &[EnumDef] = &[\n");
    for (full, e) in &enum_index {
        let values: Vec<String> = e
            .value
            .iter()
            .map(|v| format!("({:?}, {})", v.name(), v.number()))
            .collect();
        src.push_str(&format!(
            "    EnumDef {{ name: {full:?}, values: &[{}] }},\n",
            values.join(", ")
        ));
    }
    src.push_str("];\n");

    src.push_str("pub(crate) static COMPONENTS: &[ComponentDef] = &[\n");
    for proto in &protos {
        let text = std::fs::read_to_string(proto)?;
        let Some(id) = parse_ecs_component_id(&text) else {
            println!(
                "cargo:warning=no ecs_component_id in {}; skipping",
                proto.display()
            );
            continue;
        };
        let stem = proto.file_stem().unwrap().to_string_lossy();
        let pascal = pascal_case(&stem);
        let full = format!("decentraland.sdk.components.PB{pascal}");
        let Some(idx) = msg_pos(&full) else {
            println!("cargo:warning=message {full} not found; skipping component");
            continue;
        };
        src.push_str(&format!(
            "    ComponentDef {{ name: \"core::{pascal}\", id: {id}, msg: {idx} }},\n"
        ));
    }
    src.push_str("];\n");

    std::fs::write(out_dir.join("components_schema.rs"), src)
}

fn collect_messages(
    prefix: &str,
    m: &prost_types::DescriptorProto,
    msgs: &mut Vec<(String, prost_types::DescriptorProto)>,
    enums: &mut Vec<(String, prost_types::EnumDescriptorProto)>,
) {
    let full = format!("{prefix}.{}", m.name());
    msgs.push((full.clone(), m.clone()));
    for e in &m.enum_type {
        enums.push((format!("{full}.{}", e.name()), e.clone()));
    }
    for nested in &m.nested_type {
        collect_messages(&full, nested, msgs, enums);
    }
}

fn parse_ecs_component_id(proto_text: &str) -> Option<u32> {
    let idx = proto_text.find("ecs_component_id")?;
    let rest = &proto_text[idx..];
    let eq = rest.find('=')?;
    let digits: String = rest[eq + 1..]
        .trim_start()
        .chars()
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().ok()
}

fn pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel_case(snake: &str) -> String {
    let pascal = pascal_case(snake);
    let mut c = pascal.chars();
    match c.next() {
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

fn generate_abgen_embed() -> Result<()> {
    println!("cargo:rerun-if-env-changed=ABGEN_EMBED_BIN");
    let dest =
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("abgen_embed_data.rs");
    let bin = std::env::var("ABGEN_EMBED_BIN").unwrap_or_default();
    if bin.is_empty() {
        return std::fs::write(
            &dest,
            "pub static FILES: &[(&str, &[u8])] = &[];\npub const BIN_NAME: &str = \"\";\npub const TAG: &str = \"\";\n",
        );
    }
    let bin_path = PathBuf::from(&bin);
    let bin_name = bin_path
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    let dir = bin_path.parent().map(Path::to_path_buf).unwrap_or_default();
    if !bin_path.is_file() || !dir.join("template").is_dir() || !dir.join("shader").is_dir() {
        panic!(
            "ABGEN_EMBED_BIN={bin} must point at the abgen binary inside an unpacked abgen release archive (template/ and shader/ next to the binary); unset it to build without the embed"
        );
    }
    let mut rels = vec![bin_name.clone()];
    for sub in ["template", "shader"] {
        for entry in std::fs::read_dir(dir.join(sub))?.flatten() {
            if entry.path().is_file() {
                rels.push(format!("{sub}/{}", entry.file_name().to_string_lossy()));
            }
        }
    }
    for entry in std::fs::read_dir(&dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.ends_with(".dll") && entry.path().is_file() {
            rels.push(name);
        }
    }
    rels.sort();
    let mut hash: u64 = 0xcbf29ce484222325;
    let mut code = String::from("pub static FILES: &[(&str, &[u8])] = &[\n");
    for rel in &rels {
        let abs = dir.join(rel);
        println!("cargo:rerun-if-changed={}", abs.display());
        fnv1a64(&mut hash, rel.as_bytes());
        fnv1a64(&mut hash, &std::fs::read(&abs)?);
        code.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            abs.display().to_string()
        ));
    }
    code.push_str("];\n");
    code.push_str(&format!("pub const BIN_NAME: &str = {bin_name:?};\n"));
    code.push_str(&format!("pub const TAG: &str = \"{hash:016x}\";\n"));
    std::fs::write(&dest, code)
}

fn fnv1a64(hash: &mut u64, bytes: &[u8]) {
    for &b in bytes {
        *hash ^= b as u64;
        *hash = hash.wrapping_mul(0x100000001b3);
    }
}
